### ISSUE TITLE
Support for Mermaid Diagram Rendering & Width Adjustment

### ISSUE THREAD

**Issue by jerrylususu** [MartianInGreen/ChatGPT-Enhancements#1]
I recently came across your userscript, and I must say it's truly impressive! I decided to fork it and experiment with a couple of enhancements:

1. Add support for Mermaid diagram rendering
![image](https://github.com/user-attachments/assets/3f7abe15-4e5f-46f0-8d60-ecff7c9d5cee)

2. Enable adjustable width
![resize](https://github.com/user-attachments/assets/070b8576-01d6-4c72-8d9f-95d5d84c8371)

With the help of Claude, I was able to implement these features to a certain extent. However, given the complexity of the script, I'm not entirely confident about making pull requests directly. (It's quite hacky frankly.) I've made a few commits that reflect the modifications, which you can check out. It would be great if you could review them and consider integrating similar improvements into the main repository.

- mermaid: https://github.com/jerrylususu/ChatGPT-Enhancements/commit/23d9602396d924a0cbd8f4be63835cb6904a429b
- resize: https://github.com/jerrylususu/ChatGPT-Enhancements/commit/b9abe14d6162e6e031a874cc037ee08ffba0fed8

Thank you once again for creating such a useful script!

**Comment by MartianInGreen** [comment]
Hey! Thanks so much, I'll check it out! I've definitely been thinking about adding support for more types of artifacts!

**Comment by MartianInGreen** [comment]
Resizing already works btw, just a bit convoluted, you have to resize by clicking the top bar and then dragging that

**Comment by MartianInGreen** [comment]
Mermaid support added with https://github.com/MartianInGreen/ChatGPT-Enhancements/commit/f40e8d2dbe445527ee1095c36e4d4ee04907c387. :)
